type Article {
  title: String! @unique
  content: String!
  isPublished: Boolean!
  createddAt: String!
  updatedAt: String
  slug: String! @unique
  author: Author! @relation(name: "article_author")
  seo_title: String
  seo_description: String
  seo_image: String
  tags: [Tag!] @relation(name: "article_tags")
  likes: Int
  views: Int
}

type Author {
  name: String! @unique
  bio: String!
  avatar: String
  twitter: String
  github: String
  website: String
  email: String
  articles: [Article] @relation(name: "article_author")
}

type Tag {
  name: String! @unique
  articles: [Article!] @relation(name: "article_tags")
}


type Query {
  allArticles: [Article!]
  allAuthors: [Author!]
  articleBySlug(slug: String!): Article
  allTags: [Tag!]
}

input AuthorInput {
  name: String!
  bio: String!
  avatar: String
  twitter: String
  github: String
  website: String
  email: String
}

