type Article {
  title: String!
  content: String!
  published: Boolean!
  publishedAt: String!
  updatedAt: String
  slug: String!
  author: Author! @relation(name: "article_author")
  seo_title: String
  seo_description: String
  seo_image: String
  tags: [Tag!] @relation(name: "article_tags")
  likes: Int
  views: Int
}

type Tag {
  name: String!
  articles: [Article!] @relation(name: "article_tags")
}

type Author {
  name: String!
  bio: String!
  avatar: String
  twitter: String
  github: String
  website: String
  email: String
  articles: [Article] @relation(name: "article_author")
}

type Query {
  allArticles: [Article!]
  allAuthors: [Author!]
  articleBySlug(slug: String!): Article
  allTags: [Tag!]
}

input AuthorInput {
  name: String!
  bio: String!
  avatar: String
  twitter: String
  github: String
  website: String
  email: String
}

